# Site settings
title: Whisky
SEOTitle: Whisky的博客 | Elias's Blog
header-img: img/post-bg-rwd.jpg
email: helloelias@qq.com
description: "whisky's Blog"
keyword: "溺水小刀, Whisky"
url: "http://WhiskyQAQ.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/HelloElias/HelloElias.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "In me the tiger sniffs the rose."
sidebar-avatar: /img/post-bg-rwd.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings  //Social accounts
RSS: false
# weibo_username:
zhihu_username:
github_username: WhiskyQAQ
facebook_username:
jianshu_username:
#twitter_username:




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: 

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: b88d75b0c754f24705f6                            #生成的clientID
  clientSecret: 1ef9062a8b7c1d83f2be9d30b6755c5fa4973540    #生成的clientSecret
  repo: WhiskyQAQ.github.io    #仓库名称
  owner: WhiskyQAQ    #github用户名
  admin: WhiskyQAQ
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "DN",
        href: "http://www.baidu.com"
    },{
        title: "GG",
        href: "http://www.Google.com"
    },{
        title: "ZW",
        href: "http://www.cnki.net/"
    },{
        title: "CSDN",
        href: "https://www.csdn.net/"
    }
]
